/**
 * Types for npm package.json generation from SFPM packages.
 *
 * When publishing to npm, SFPM packages are represented as standard npm packages
 * with SFPM-specific metadata stored under the "sfpm" property.
 */

import {PackageType, SfpmPackageMetadataBase} from './package.js';

/**
 * The "sfpm" property in package.json.
 * Contains all SFPM-specific metadata that doesn't map to standard npm fields.
 */
export interface NpmPackageSfpmMetadata {
  /** Salesforce API version */
  apiVersion?: string;
  /** Build timestamp */
  buildDate?: string;
  /** Git commit SHA */
  commitId?: string;
  /** Whether this is an org-dependent unlocked package */
  isOrgDependent?: boolean;
  /** Full SFPM metadata (optional, for advanced use cases) */
  metadata?: SfpmPackageMetadataBase;
  /** Namespace prefix if applicable */
  namespacePrefix?: string;
  /** Salesforce Package ID (0Ho...) for unlocked packages */
  packageId?: string;
  /** Package type (unlocked, source, data) */
  packageType: string;
  /** Salesforce Package Version ID (04t...) for unlocked packages */
  packageVersionId?: string;
  /** SHA-256 hash of the source files */
  sourceHash?: string;
}

/**
 * Standard npm package.json structure as generated by SFPM.
 *
 * @see https://docs.npmjs.com/cli/v10/configuring-npm/package-json
 */
export interface NpmPackageJson {
  /** Author information */
  author?: string;
  /** Issue/bug tracker URL */
  bugs?: {
    url: string;
  };
  /** Package description from versionDescription */
  description?: string;
  /**
   * Files to include in the package.
   * SFPM includes source, scripts, manifests, and sfdx-project.json.
   */
  files?: string[];
  /** Homepage URL (e.g., AppExchange listing or project docs) */
  homepage?: string;
  /** Package keywords for discovery */
  keywords?: string[];
  /** License identifier */
  license?: string;
  /** Main entry point (stub for SFPM packages) */
  main?: string;
  /**
   * Managed package dependencies pinned to a subscriber packageVersionId (04t...).
   * These are Salesforce managed packages identified by their alias in
   * sfdx-project.json (e.g., "Nebula Logger@4.16.0") and cannot be resolved via npm.
   */
  managedDependencies?: Record<string, string>;
  /** Scoped package name (e.g., "@myorg/my-package") */
  name: string;
  /**
   * Optional dependencies - used for versioned SFPM package dependencies.
   * "Optional" because they may not yet be published to the npm registry.
   */
  optionalDependencies?: Record<string, string>;
  /** Repository URL */
  repository?: {
    type: string;
    url: string;
  };
  /**
   * SFPM-specific metadata.
   * Contains package type, IDs, and other Salesforce-specific info.
   */
  sfpm: SfpmPackageMetadataBase;
  /** Semver version (e.g., "1.0.0-1") */
  version: string;
}

/**
 * Options for generating package.json
 */
export interface PackageJsonGeneratorOptions {
  /** Additional keywords to include */
  additionalKeywords?: string[];
  /** Author string */
  author?: string;
  /** License identifier */
  license?: string;
  /** npm scope (e.g., "@myorg") - required */
  npmScope: string;
  /** Source hash to include in metadata */
  sourceHash?: string;
}

/**
 * Converts an SFPM dependency to npm optionalDependency format.
 *
 * sfdx-project.json format:
 *   { "package": "my-dependency", "versionNumber": "1.2.0.LATEST" }
 *
 * npm format:
 *   { "@scope/my-dependency": "^1.2.0" }
 *
 * @param dep - Dependency from sfdx-project.json
 * @param npmScope - npm scope to use
 * @returns Tuple of [packageName, versionRange]
 */
export function convertDependencyToNpm(
  dep: {package: string; versionNumber?: string},
  npmScope: string,
): [string, string] {
  const npmPackageName = `${npmScope}/${dep.package}`;

  // Extract base version (major.minor.patch) from sfdx version format
  // "1.2.0.LATEST" -> "^1.2.0"
  // "1.2.0.4" -> "^1.2.0"
  // "1.2.0" -> "^1.2.0"
  let versionRange = '*';

  if (dep.versionNumber) {
    const parts = dep.versionNumber.split('.');
    if (parts.length >= 3) {
      const baseVersion = parts.slice(0, 3).join('.');
      versionRange = `^${baseVersion}`;
    }
  }

  return [npmPackageName, versionRange];
}
