import type {Logger} from '@b64hub/sfpm-core';

import {OrgTypes} from '@salesforce/core';

import type {PoolOrg} from '../org/pool-org.js';

/**
 * Config-friendly pool type — accepts plain strings so users
 * don't need to import `OrgTypes` from `@salesforce/core`.
 *
 * Internally the core always compares against `OrgTypes` enum values,
 * which are identical at runtime (`OrgTypes.Scratch === 'scratch'`).
 */
export type PoolType = 'sandbox' | 'scratch' | OrgTypes;

/**
 * Pool sizing configuration — how many orgs to maintain.
 *
 * `minAllocation` and `maxAllocation` define the target range.
 * The pool manager ensures the pool stays within these bounds.
 */
export interface PoolSize {
  /** Number of orgs to create per provisioning batch (default: 5) */
  batch?: number;
  /** Maximum number of orgs in the pool */
  max: number;
  /** Minimum number of orgs to maintain (default: 0) */
  min?: number;
}

export interface NetworkSettings {
  /** Specific IP ranges to relax (true = all, array = specific ranges) */
  relaxIPRanges?: boolean | string[];
}

/**
 * Shared pool configuration fields common to all pool types.
 *
 * Extracted so that `ScratchOrgPoolConfig` and `SandboxPoolConfig`
 * don't duplicate these properties.
 */
export interface PoolConfigBase {
  /** Path to the org definition file (scratch org or sandbox) */
  definitionFile: string;
  /** Deployment behavior for freshly provisioned orgs */
  deployment?: {
    /** Continue pool provisioning even if deployment fails (default: false) */
    continueOnError?: boolean;
    /** Whether to enable source tracking in the org (default: false) */
    enableSourceTracking?: boolean;
    /** Skip updating Sfpm_Artifact__c custom setting after deployment (default: false) */
    skipArtifactUpdate?: boolean;
    /** Apex test level for deployments (default: NoTestRun) */
    testLevel?: string;
  };
  /** Max retries on transient creation failures (default: 3) */
  maxRetries?: number;
  /** Network/IP relaxation settings */
  network?: NetworkSettings;
  /** Pool sizing constraints */
  sizing: PoolSize;
  /** Use an existing snapshot pool as a base (pool tag) */
  snapshotPool?: string;
  type: PoolType;
  /** Max minutes to wait for org creation (default: 30) */
  waitMinutes?: number;
}

/**
 * Pool configuration for scratch org pools.
 *
 * @example
 * ```typescript
 * const pool: ScratchOrgPoolConfig = {
 *   type: OrgTypes.Scratch,
 *   definitionFile: 'config/project-scratch-def.json',
 *   expiryDays: 7,
 *   sizing: { max: 10, min: 2, batch: 5 },
 * };
 * ```
 */
export interface ScratchOrgPoolConfig extends PoolConfigBase {
  /** Number of days until scratch orgs expire (default: 7) */
  expiryDays?: number;
  /** Whether to exclude ancestor package versions (default: false) */
  noAncestors?: boolean;
  type: 'scratch' | OrgTypes.Scratch;
}

/**
 * Pool configuration for sandbox pools.
 *
 * Sandbox creation settings (licenseType, apexClassId, etc.) live in
 * the sandbox definition file. This config only holds pool operation
 * concerns.
 *
 * @example
 * ```typescript
 * const pool: SandboxPoolConfig = {
 *   type: OrgTypes.Sandbox,
 *   definitionFile: 'config/sandbox-def.json',
 *   namePattern: 'SB',
 *   sizing: { max: 5, batch: 2 },
 * };
 * ```
 */
export interface SandboxPoolConfig extends PoolConfigBase {
  /**
   * Override for the sandbox name prefix from the definition file.
   *
   * When set, takes precedence over `sandboxName` in the definition file.
   * During provisioning, concrete names are generated by appending
   * an index (e.g., `SB1`, `SB2`). Must be a valid Salesforce
   * sandbox name prefix (alphanumeric, max 10 chars).
   */
  namePattern?: string;
  type: 'sandbox' | OrgTypes.Sandbox;
}

/**
 * Discriminated union of pool configurations.
 *
 * Discriminated by the `type` field — `OrgTypes.Scratch` or
 * `OrgTypes.Sandbox`.
 */
export type PoolConfig = SandboxPoolConfig | ScratchOrgPoolConfig;

/** Default pool sizing when not explicitly configured. */
export const DEFAULT_POOL_SIZING: Required<Pick<PoolSize, 'batch' | 'min'>> = {
  batch: 5,
  min: 0,
};

/**
 * Handles authentication to orgs fetched from a pool.
 *
 * The primary authentication mechanism is the SFDX auth URL stored
 * on the org's hub record (`Auth_Url__c` on `ScratchOrgInfo` for
 * scratch orgs, or `Sandbox_Pool_Org__c` for sandboxes). When an
 * auth URL is not available, implementations may fall back to JWT
 * `parentUsername` (scratch orgs) or other mechanisms.
 *
 * Implement at the CLI layer where `@salesforce/core` is available.
 * The adapter is provided via DI to `PoolFetcher`.
 */
export interface PoolOrgAuthenticator {
  /** Enable source tracking for a claimed org */
  enableSourceTracking?(org: PoolOrg): Promise<void>;

  /** Whether the org has valid authentication credentials */
  hasValidAuth(org: PoolOrg): boolean;

  /** Authenticate to an org (auth URL first, JWT fallback). */
  login(org: PoolOrg): Promise<void>;
}

/**
 * Action to execute after an org has been claimed from the pool.
 *
 * Post-claim actions form a composable pipeline — each action runs
 * in order after a successful claim. Common actions include:
 * - Authentication (`authenticator.login`)
 * - Source tracking setup (`authenticator.enableSourceTracking`)
 * - Sharing via email (`devHub.shareOrg`)
 *
 * The caller (CLI, factory, actions) composes the appropriate set of
 * actions based on the use case.
 *
 * @param org - The claimed org
 */
export type PostClaimAction = (org: PoolOrg) => Promise<void>;

/**
 * Options for fetching orgs from a pool.
 *
 * Used for both single-org fetch (claims via optimistic concurrency)
 * and multi-org fetch (no claiming — caller manages allocation).
 *
 * Authentication and other post-claim behaviors are composed via
 * `postClaimActions` rather than baked into the fetcher. The caller
 * decides which actions to include.
 */
export interface PoolFetchOptions {
  /** Maximum number of orgs to fetch (only used with fetchAll) */
  limit?: number;
  /** Only return orgs owned by the current user */
  myPool?: boolean;
  /**
   * Pipeline of actions to run after claiming/fetching.
   *
   * Actions run sequentially per org, but different orgs are processed
   * in parallel. If any action throws for an org, that org is filtered
   * out of the result. Non-fatal actions should catch internally and log.
   *
   * @example
   * ```typescript
   * {
   *   postClaimActions: [
   *     (org) => authenticator.login(org),
   *     (org) => authenticator.enableSourceTracking(org),
   *   ]
   * }
   * ```
   */
  postClaimActions?: PostClaimAction[];
}

// ============================================================================
// Pool Deletion
// ============================================================================

/**
 * Options for deleting orgs from a pool.
 */
export interface PoolDeleteOptions {
  /** Only delete orgs with 'In_Progress' allocation status */
  inProgressOnly?: boolean;
  /** Only delete orgs owned by the current user */
  myPool?: boolean;
}

// ============================================================================
// Pool Task Execution
// ============================================================================

/**
 * A unit of work to perform on a provisioned org.
 *
 * Tasks run after org creation during pool provisioning — deploying
 * packages, running scripts, configuring permissions, etc.
 *
 * Each task receives a `Logger` scoped to the org it operates on.
 * Tasks are executed in the order they are registered. If a task fails
 * and its `continueOnError` property is `false` (the default), the
 * remaining tasks for that org are skipped.
 *
 * @example
 * ```typescript
 * const deployTask: PoolOrgTask = {
 *   name: 'deploy-packages',
 *   async execute(org, logger) {
 *     logger.info(`Deploying to ${org.auth.username}...`);
 *     await deployPackages(org);
 *     logger.info('Deployment complete');
 *     return { success: true };
 *   },
 * };
 * ```
 */
export interface PoolOrgTask {
  /**
   * Whether provisioning should continue if this task fails.
   *
   * When `true`, the failure is recorded but subsequent tasks
   * still run. When `false` (default), remaining tasks for this
   * org are skipped on failure.
   */
  continueOnError?: boolean;

  /**
   * Execute the task against a provisioned org.
   *
   * @param org - The provisioned org to operate on
   * @param logger - A logger scoped to this org (output destination
   *                 is determined by the `PoolOrgLoggerFactory`)
   * @returns Result indicating success or failure with details
   */
  execute(org: PoolOrg, logger: Logger): Promise<PoolOrgTaskResult>;

  /** Human-readable task name, used in events and log prefixes */
  name: string;
}

/**
 * Result of a single task execution on an org.
 */
export interface PoolOrgTaskResult {
  /** Error message when `success` is false */
  error?: string;
  /** Whether the task completed successfully */
  success: boolean;
}

/**
 * Factory for creating loggers scoped to individual pool orgs.
 *
 * Injected into the pool manager to control where per-org preparation
 * logs are written. The factory is called once per org before
 * task execution begins.
 *
 * @example
 * ```typescript
 * class FileLoggerFactory implements PoolOrgLoggerFactory {
 *   constructor(private readonly baseDir: string) {}
 *
 *   create(org: PoolOrg): Logger {
 *     const logPath = path.join(this.baseDir, `${org.auth.alias}.log`);
 *     return createFileLogger(logPath);
 *   }
 *
 *   async dispose(): Promise<void> {
 *     // Flush and close all file handles
 *   }
 * }
 * ```
 */
export interface PoolOrgLoggerFactory {
  /** Create a logger scoped to a specific org */
  create(org: PoolOrg): Logger;

  /**
   * Clean up resources after all tasks have completed.
   *
   * Called once at the end of the provisioning run. Use this to
   * flush file handles, upload artifacts, or finalize structured
   * output.
   */
  dispose?(): Promise<void>;
}

// ============================================================================
// Pool Runtime State
// ============================================================================

/**
 * Ephemeral state tracked during a pool provisioning run.
 *
 * This is NOT configuration — it is computed at runtime by the pool
 * manager and should never appear in `sfpm.config.ts`.
 */
export interface PoolProvisioningState {
  /** Current number of active orgs in the pool */
  currentAllocation: number;
  /** Number of orgs that failed to create in this run */
  failedToCreate: number;
  /** Orgs currently in the pool */
  orgs: PoolOrg[];
  /** Number of orgs that need to be created to reach target */
  toAllocate: number;
  /** Number needed to satisfy maximum allocation */
  toSatisfyMax: number;
  /** Number needed to satisfy minimum allocation */
  toSatisfyMin: number;
}
