import { simpleGit, SimpleGit } from 'simple-git';
import fs from 'fs-extra';
import path from 'path';
import ignore from 'ignore';
import tmp from 'tmp';

import { Logger } from '../types/logger.js';

export default class Git {
    private _git: SimpleGit;
    private repositoryLocation: string;
    private tempRepoLocation: any;
    private _isATemporaryRepo: boolean = false;
    private logger?: Logger;

    public constructor(private projectDir?: string, logger?: Logger) {
        if (this.projectDir) {
            this._git = simpleGit(this.projectDir);
            this.repositoryLocation = this.projectDir;
        } else {
            this._git = simpleGit();
            this.repositoryLocation = process.cwd();
        }

        this.logger = logger;
    }

    async fetch() {
        return this._git.fetch('origin');
    }

    async getHeadCommit(): Promise<string> {
        return this._git.revparse(['HEAD']);
    }

    async getBaseBranchCommit(baseBranch: string): Promise<string> {
        return this._git.revparse([baseBranch]);
    }

    async show(options: string[]): Promise<string> {
        return this._git.show(options);
    }

    async tag(options: string[]): Promise<string[]> {
        let tagResult = await this._git.tag(options);

        let temp: string[] = tagResult.split('\n');
        temp.pop();

        return temp;
    }

    async diff(options: string[]): Promise<string[]> {
        let diffResult = await this._git.diff(options);

        let temp: string[] = diffResult.split('\n');
        temp.pop();

        return temp;
    }

    async log(options: string[]): Promise<string[]> {
        let gitLogResult = await this._git.log(options);

        return gitLogResult['all'][0]['hash'].split('\n');
    }

    public async getRemoteOriginUrl(overrideOriginURL?: string): Promise<string> {
        let remoteOriginURL;
        if (!overrideOriginURL) {
            remoteOriginURL = (await this._git.getConfig('remote.origin.url')).value;
            if (!remoteOriginURL) {
                remoteOriginURL = (await this._git.getConfig('remote.origin.url')).value;
            }
            this.logger?.debug(`Fetched Remote URL ${remoteOriginURL}`);
        } else remoteOriginURL = overrideOriginURL;

        if (!remoteOriginURL) throw new Error('Remote origin must be set in repository');

        return remoteOriginURL;
    }

    public async commitFile(pathToFiles: string[], message = `[skip ci] Autogenerated commit by sfpm`) {
        try {
            await this._git.add(pathToFiles);
            await this._git.commit(message);
            this.logger?.info(`Committed File ${pathToFiles}`);
        } catch (error) {
            this.logger?.error(
                `Unable to commit file, probably due to no change or something else,Please try manually`
            );
            throw error;
        }
    }

    async pushTags(tags?: string[]) {
        if (!tags) await this._git.pushTags();
        else {
            for (let tag of tags) {
                await this._git.push('origin', tag);
            }
        }
    }

    async deleteTags(tags?: string[]) {
        if (tags) await this._git.push('origin', '--delete', tags);
    }

    async addAnnotatedTag(tagName: string, annotation: string, commitId?: string) {
        try {
            if (!commitId) {
                await this._git.addAnnotatedTag(tagName, annotation);
            } else {
                const commands = ['tag', tagName, commitId, '-m', annotation];
                await this._git.raw(commands);
            }
            this.logger?.info(`Added annotated tag ${tagName}`);
        } catch (error) {
            this.logger?.error(
                `Unable to add tag ${tagName}, probably due to existing tag or something else, Please try manually`
            );
            throw error;
        }
    }

    async isBranchExists(branch: string): Promise<boolean> {
        const listOfBranches = await this._git.branch(['-la']);

        return listOfBranches.all.find((elem) => elem.endsWith(branch)) ? true : false;
    }

    static async initiateRepoAtTempLocation(logger: Logger, commitRef?: string, branch?: string): Promise<Git> {
        let locationOfCopiedDirectory = tmp.dirSync({ unsafeCleanup: true });

        logger.info(`Copying the repository to ${locationOfCopiedDirectory.name}`);
        let repoDir = locationOfCopiedDirectory.name;

        // Copy source directory to temp dir
        const gitignore = ignore();
        const gitignorePath = path.join(process.cwd(), '.gitignore');
        if (fs.existsSync(gitignorePath)) {
            const gitignoreContent = fs.readFileSync(gitignorePath).toString();
            gitignore.add(gitignoreContent);
        }

        // Copy source directory to temp dir respecting .gitignore
        fs.copySync(process.cwd(), repoDir, {
            filter: (src) => {
                const relativePath = path.relative(process.cwd(), src);

                // Always include root directory
                if (!relativePath) {
                    return true;
                }

                // Check if file should be ignored
                return !gitignore.ignores(relativePath);
            },
        });

        //Initiate git on new repo on using the abstracted object
        let git = new Git(repoDir, logger);
        git._isATemporaryRepo = true;
        git.tempRepoLocation = locationOfCopiedDirectory;

        await git.addSafeConfig(repoDir);
        await git.getRemoteOriginUrl();
        await git.fetch();
        if (branch) {
            await git.createBranch(branch);
        }
        if (commitRef) {
            await git.checkout(commitRef, true);
        }

        logger.info(
            `Successfully created temporary repository at ${repoDir} with commit ${commitRef ? commitRef : 'HEAD'}`
        );
        return git;
    }

    static async initiateRepo(logger?: Logger, projectDir?: string) {
        let git = new Git(projectDir, logger);
        if (projectDir) await git.addSafeConfig(projectDir);
        else {
            await git.addSafeConfig(process.cwd());
        }
        await git.getRemoteOriginUrl();
        return git;
    }

    public raw(commands: string[]) {
        return this._git.raw(commands);
    }

    public getRepositoryPath() {
        return this.repositoryLocation;
    }

    async deleteTempRepoIfAny() {
        if (this.tempRepoLocation) this.tempRepoLocation.removeCallback();
    }

    async addSafeConfig(repoDir: string) {
        try {
            //add workaround for safe directory (https://github.com/actions/runner/issues/2033)
            await this._git.addConfig('safe.directory', repoDir, false, 'global');
        } catch (error) {
            //ignore error
            this.logger?.trace(`Unable to set safe.directory`)
        }
    }

    async pushToRemote(branch: string, isForce: boolean) {
        if (!branch) branch = (await this._git.branch()).current;
        this.logger?.info(`Pushing ${branch}`);
        if (process.env.SFPM_OVERRIDE_ORIGIN_URL) {
            await this._git.removeRemote('origin');
            await this._git.addRemote('origin', process.env.SFPM_OVERRIDE_ORIGIN_URL);
        }

        if (isForce) {
            await this._git.push('origin', branch, [`--force`]);
        } else {
            await this._git.push('origin', branch);
        }
    }

    isTempRepo(): boolean {
        return this._isATemporaryRepo;
    }

    async getCurrentCommitId() {
        return this._git.revparse(['HEAD']);
    }

    async checkout(commitRef: string, isForce?: boolean) {
        if (isForce) {
            return this._git.checkout(commitRef, [`--force`]);
        } else return this._git.checkout(commitRef, {});
    }

    async checkoutPath(commitRef: string, path: string, isForce?: boolean) {
        if (isForce) {
            return this._git.checkout(commitRef, [path, `--force`]);
        } else return this._git.checkout(commitRef, [path]);
    }

    async stageChangedFiles(path: string): Promise<boolean> {
        try {
            await this._git.add(path);
            return true;
        } catch (error) {
            this.logger?.info(`Nothing to add, ignoring`);
            return false;
        }
    }
    async createBranch(branch: string) {
        if (await this.isBranchExists(branch)) {
            await this._git.checkout(branch, ['-f']);
            try {
                // For ease-of-use when running locally and local branch exists
                await this._git.merge([`refs/remotes/origin/${branch}`]);
            } catch (error) {
                this.logger?.trace(`Unable to find remote`);
            }
        } else {
            await this._git.checkout(['-b', branch]);
        }
    }
}
