import type {PoolOrg, PoolOrgInfo} from '../pool-org.js';

// ============================================================================
// Sandbox Domain Types
// ============================================================================

/**
 * Pool metadata for a sandbox, extending the base with sandbox-specific fields.
 */
export interface SandboxPoolInfo extends PoolOrgInfo {
  /** Group whose members may access this sandbox. */
  groupId?: string;
}

/**
 * A sandbox managed by a pool.
 *
 * Extends `PoolOrg` with a fixed `kind` discriminant and a richer
 * `pool` shape that includes `groupId`.
 */
export interface Sandbox extends PoolOrg {
  readonly orgType: 'sandbox';
  pool?: SandboxPoolInfo;
}

// ============================================================================
// Sandbox Configuration
// ============================================================================

/**
 * Sandbox license types supported by Salesforce.
 *
 * Maps to the `LicenseType` field on `SandboxInfo`.
 */
export type SandboxLicenseType = 'DEVELOPER' | 'DEVELOPER PRO' | 'FULL' | 'PARTIAL';

/**
 * Sandbox creation defaults used when provisioning sandboxes for a pool.
 *
 * These settings control how individual sandboxes are created via the
 * `Org.createSandbox()` SDK method.
 *
 * @example
 * ```typescript
 * const defaults: SandboxDefaults = {
 *   namePattern: 'SB',
 *   licenseType: 'DEVELOPER',
 *   groupId: '0GR000000000001',
 * };
 * ```
 */
export interface SandboxDefaults {
  /** Apex class ID to run after sandbox creation (post-copy script) */
  apexClassId?: string;
  /** Whether to auto-activate the sandbox after creation (default: true) */
  autoActivate?: boolean;
  /**
   * ID of the group whose members can access created sandboxes.
   *
   * Maps to `SandboxRequest.ActivationUserGroupId`. In a pool scenario
   * this allows a CICD user to create sandboxes that team members can
   * later claim and access without ownership transfer.
   */
  groupId?: string;
  /** Sandbox license type (default: 'DEVELOPER') */
  licenseType: SandboxLicenseType;
  /** Max retries on transient creation failures (default: 3) */
  maxRetries?: number;
  /**
   * Name pattern prefix for sandbox names.
   *
   * During provisioning, concrete names are generated by appending
   * an index (e.g., `SB1`, `SB2`). Must be a valid Salesforce
   * sandbox name prefix (alphanumeric, max 10 chars).
   */
  namePattern: string;
  /**
   * Name of an existing sandbox to use as a source.
   *
   * When set, `Org.cloneSandbox()` is used instead of `Org.createSandbox()`.
   */
  sourceSandboxName?: string;
  /** Max minutes to wait for sandbox creation (default: 30) */
  waitMinutes?: number;
}

/** Default sandbox creation settings. */
export const DEFAULT_SANDBOX: Required<Pick<SandboxDefaults, 'autoActivate' | 'licenseType' | 'maxRetries' | 'waitMinutes'>> = {
  autoActivate: true,
  licenseType: 'DEVELOPER',
  maxRetries: 3,
  waitMinutes: 30,
};

// ============================================================================
// Sandbox Create Types
// ============================================================================

/**
 * Configuration for creating a sandbox.
 *
 * Maps to the `SandboxRequest` type from `@salesforce/core` with
 * pool-specific additions.
 */
export interface SandboxCreateRequest {
  /** Group ID for sandbox access (maps to `ActivationUserGroupId`) */
  activationUserGroupId?: string;
  /** Apex class ID for post-copy script */
  apexClassId?: string;
  /** Whether to auto-activate (default: true) */
  autoActivate?: boolean;
  /** License type */
  licenseType: SandboxLicenseType;
  /** Number of retries on transient failures */
  retries?: number;
  /** Sandbox name (unique within the production org) */
  sandboxName: string;
  /** Source sandbox name for cloning */
  sourceSandboxName?: string;
  /** Max minutes to wait for creation */
  waitMinutes?: number;
}

/**
 * Result returned after sandbox creation.
 *
 * Maps key fields from the SDK's `SandboxProcessObject`.
 */
export interface SandboxCreateResult {
  /** Login URL for the sandbox */
  loginUrl: string;
  /** The 18-character org ID of the sandbox */
  orgId: string;
  /** Sandbox name */
  sandboxName: string;
  /** The sandbox process ID */
  sandboxProcessId: string;
  /** Username for the sandbox */
  username: string;
}

/**
 * Pool-level options for creating a sandbox.
 *
 * Used by `SandboxProvider.createOrg()`. Maps to the SDK's sandbox
 * creation methods internally.
 */
export interface SandboxCreateOptions {
  /** Group ID for sandbox access */
  activationUserGroupId?: string;
  /** Local alias for the sandbox */
  alias: string;
  /** Apex class ID for post-copy script */
  apexClassId?: string;
  /** Whether to auto-activate the sandbox */
  autoActivate?: boolean;
  /** Sandbox license type */
  licenseType?: string;
  /** Max retries on transient failures */
  retries?: number;
  /** Sandbox name */
  sandboxName?: string;
  /** Source sandbox name for cloning */
  sourceSandboxName?: string;
  /** Max minutes to wait for creation */
  waitMinutes?: number;
}
