import {OrgTypes, SandboxInfo} from '@salesforce/core';

import type {PoolOrg, PoolOrgInfo} from '../pool-org.js';

/**
 * Pool metadata for a sandbox, extending the base with sandbox-specific fields.
 */
export interface SandboxPoolInfo extends PoolOrgInfo {
  /** Group whose members may access this sandbox. */
  groupId?: string;
}

/**
 * A sandbox managed by a pool.
 *
 * Extends `PoolOrg` with a fixed `kind` discriminant and a richer
 * `pool` shape that includes `groupId`.
 */
export interface Sandbox extends PoolOrg {
  readonly orgType: OrgTypes.Sandbox;
  pool?: SandboxPoolInfo;
}

/**
 * Sandbox license types supported by Salesforce.
 *
 * Maps to the `LicenseType` field on `SandboxInfo`.
 */
export type SandboxLicenseType = SandboxInfo['LicenseType'];

/**
 * Sandbox definition file schema.
 *
 * Matches the JSON structure defined in the Salesforce CLI sandbox
 * definition file spec. This is the source of truth for how a sandbox
 * is configured — pool operations only add naming and lifecycle concerns.
 *
 * @see https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_sandbox_definition.htm
 */
export interface SandboxDefinition {
  activationUserGroupId?: string;
  activationUserGroupName?: string;
  apexClassId?: string;
  apexClassName?: string;
  autoActivate?: boolean;
  copyArchivedActivities?: boolean;
  copyChatter?: boolean;
  description?: string;
  features?: string;
  historyDays?: number;
  licenseType?: SandboxLicenseType;
  sandboxName: string;
  sourceId?: string;
  sourceSandboxName?: string;
  templateId?: string;
}

/**
 * Pool-level sandbox defaults used when provisioning sandboxes.
 *
 * Sandbox creation settings (licenseType, apexClassId, groupName, etc.)
 * live in the sandbox definition file — this type only holds pool
 * operation concerns: where to find the definition, naming overrides,
 * and timeouts.
 *
 * @example
 * ```typescript
 * const defaults: SandboxDefaults = {
 *   definitionFile: 'config/sandbox-def.json',
 *   namePattern: 'DEVBOX',
 * };
 * ```
 */
export interface SandboxDefaults {
  /** Path to the sandbox definition file (e.g., `config/sandbox-def.json`) */
  definitionFile: string;
  /** Max retries on transient creation failures (default: 3) */
  maxRetries?: number;
  /**
   * Override for the sandbox name prefix from the definition file.
   *
   * When set, takes precedence over `sandboxName` in the definition file.
   * During provisioning, concrete names are generated by appending
   * an index (e.g., `SB1`, `SB2`). Must be a valid Salesforce
   * sandbox name prefix (alphanumeric, max 10 chars).
   */
  namePattern?: string;
  /** Max minutes to wait for sandbox creation (default: 30) */
  waitMinutes?: number;
}

/** Default sandbox pool operation settings. */
export const DEFAULT_SANDBOX = {
  maxRetries: 3,
  waitMinutes: 30,
};

/**
 * Pool-level options for creating a sandbox.
 *
 * Used by `SandboxProvider.createOrg()`. The provider reads the
 * definition file, resolves the sandbox name from `namePattern`
 * or the definition's `sandboxName`, and builds the SDK request.
 */
export interface SandboxCreateOptions {
  /** Local alias for the sandbox (e.g., SO1, SO2) */
  alias: string;
  /** Path to the sandbox definition file */
  definitionFile: string;
  /** Override for the sandbox name prefix from the definition file */
  namePattern?: string;
  /** Max minutes to wait for creation */
  waitMinutes?: number;
}
